### PR TITLE
Student Management System

### LINKED ISSUE #16: Project add- Student management system
Hey, I am going to create a student management system in solidity where we can manage student data. can I work on this?

### PR DESCRIPTION
**Pull request by Engineervinay**
Student management system to store and retrieve data of students. 
Fixes #16 
Screenshot (30)

### CODE REVIEW

**Comment by Engineervinay** [comment]
Hey @ismailbangee  thank you so much for letting me contribute. please add hacktoberfest tag while accepting PR.

**Comment by ismailbangee** [comment]
Hello

Kindly follow commit comments as mentioned here.

https://github.com/ismailbangee/smart-contracts/blob/main/CONTRIBUTING.md

**Comment by Engineervinay** [comment]
> Hello
> 
> Kindly follow commit comments as mentioned here.
> 
> https://github.com/ismailbangee/smart-contracts/blob/main/CONTRIBUTING.md

Okay 👍 I'll make the changes

**Comment by ismailbangee** [comment]
Looking forward to it. Kindly send me new pull request.

**Comment by Engineervinay** [comment]
> Looking forward to it. Kindly send me new pull request.

Okay, I'll delete this one and create a new one.

**Pull request closed without merging**
